<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **SpaceX  Falcon 9 first stage Landing Prediction**

# Lab 1: Collecting the data

Estimated time needed: **45** minutes

In this capstone, we will predict if the Falcon 9 first stage will land successfully. SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars; other providers cost upward of 165 million dollars each, much of the savings is because SpaceX can reuse the first stage. Therefore if we can determine if the first stage will land, we can determine the cost of a launch. This information can be used if an alternate company wants to bid against SpaceX for a rocket launch. In this lab, you will collect and make sure the data is in the correct format from an API. The following is an example of a successful and launch.

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/lab_v2/images/landing_1.gif)

Several examples of an unsuccessful landing are shown here:

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/lab_v2/images/crash.gif)

Most unsuccessful landings are planned. Space X performs a controlled landing in the oceans.

## Objectives

In this lab, you will make a get request to the SpaceX API. You will also do some basic data wrangling and formating. 

- Request to the SpaceX API
- Clean the requested data

----

## Import Libraries and Define Auxiliary Functions

We will import the following libraries into the lab

In [1]:
# Requests allows us to make HTTP requests which we will use to get data from an API
import requests
# Pandas is a software library written for the Python programming language for data manipulation and analysis.
import pandas as pd
# NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays
import numpy as np
# Datetime is a library that allows us to represent dates
import datetime

# Setting this option will print all collumns of a dataframe
pd.set_option('display.max_columns', None)
# Setting this option will print all of the data in a feature
pd.set_option('display.max_colwidth', None)

Below we will define a series of helper functions that will help us use the API to extract information using identification numbers in the launch data.

From the <code>rocket</code> column we would like to learn the booster name.

In [2]:
# Takes the dataset and uses the rocket column to call the API and append the data to the list
def getBoosterVersion(data):
    for x in data['rocket']:
       if x:
        response = requests.get("https://api.spacexdata.com/v4/rockets/"+str(x)).json()
        BoosterVersion.append(response['name'])

From the <code>launchpad</code> we would like to know the name of the launch site being used, the logitude, and the latitude.

In [3]:
# Takes the dataset and uses the launchpad column to call the API and append the data to the list
def getLaunchSite(data):
    for x in data['launchpad']:
       if x:
         response = requests.get("https://api.spacexdata.com/v4/launchpads/"+str(x)).json()
         Longitude.append(response['longitude'])
         Latitude.append(response['latitude'])
         LaunchSite.append(response['name'])

From the <code>payload</code> we would like to learn the mass of the payload and the orbit that it is going to.

In [4]:
# Takes the dataset and uses the payloads column to call the API and append the data to the lists
def getPayloadData(data):
    for load in data['payloads']:
       if load:
        response = requests.get("https://api.spacexdata.com/v4/payloads/"+load).json()
        PayloadMass.append(response['mass_kg'])
        Orbit.append(response['orbit'])

From <code>cores</code> we would like to learn the outcome of the landing, the type of the landing, number of flights with that core, whether gridfins were used, wheter the core is reused, wheter legs were used, the landing pad used, the block of the core which is a number used to seperate version of cores, the number of times this specific core has been reused, and the serial of the core.

In [5]:
# Takes the dataset and uses the cores column to call the API and append the data to the lists
def getCoreData(data):
    for core in data['cores']:
            if core['core'] != None:
                response = requests.get("https://api.spacexdata.com/v4/cores/"+core['core']).json()
                Block.append(response['block'])
                ReusedCount.append(response['reuse_count'])
                Serial.append(response['serial'])
            else:
                Block.append(None)
                ReusedCount.append(None)
                Serial.append(None)
            Outcome.append(str(core['landing_success'])+' '+str(core['landing_type']))
            Flights.append(core['flight'])
            GridFins.append(core['gridfins'])
            Reused.append(core['reused'])
            Legs.append(core['legs'])
            LandingPad.append(core['landpad'])

Now let's start requesting rocket launch data from SpaceX API with the following URL:

In [6]:
spacex_url="https://api.spacexdata.com/v4/launches/past"

In [7]:
response = requests.get(spacex_url)

Check the content of the response

In [8]:
print(response.content)

b'[{"fairings":{"reused":false,"recovery_attempt":false,"recovered":false,"ships":[]},"links":{"patch":{"small":"https://images2.imgbox.com/94/f2/kktrAanz_o.png","large":"https://images2.imgbox.com/5b/02/QcxHnwlg_o.png"},"reddit":{"campaign":null,"launch":null,"media":null,"recovery":null},"flickr":{"small":[],"original":[]},"presskit":null,"webcast":"https://www.youtube.com/watch?v=0a_00nJ_Y88","youtube_id":"0a_00nJ_Y88","article":"https://www.space.com/2196-spacex-inaugural-falcon-1-rocket-lost-launch.html","wikipedia":"https://en.wikipedia.org/wiki/DemoSat"},"static_fire_date_utc":"2006-03-17T00:00:00.000Z","static_fire_date_unix":1142553600,"net":false,"window":0,"rocket":"5e9d0d95eda69955f709d1eb","success":false,"failures":[{"time":33,"altitude":null,"reason":"merlin engine failure"}],"details":"Engine failure at 33 seconds and loss of vehicle","crew":[],"ships":[],"capsules":[],"payloads":["5eb0e4b5b6c3bb0006eeb1e1"],"launchpad":"5e9e4502f5090995de566f86","flight_number":1,"name":"FalconSat","date_utc":"2006-03-24T22:30:00.000Z" ...'

You should see the response contains massive information about SpaceX launches. Next, let's try to discover some more relevant information for this project.

### Task 1: Request and parse the SpaceX launch data using the GET request

To make the requested JSON results more consistent, we will use the following static response object for this project:

In [9]:
static_json_url='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/API_call_spacex_api.json'

We should see that the request was successfull with the 200 status response code

In [10]:
response=requests.get(static_json_url)

In [11]:
response.status_code

200

Now we decode the response content as a Json using <code>.json()</code> and turn it into a Pandas dataframe using <code>.json_normalize()</code>

In [12]:
import pandas as pd
import requests

# Static JSON URL with SpaceX launch data
static_json_url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/API_call_spacex_api.json'

# Step 1: Make the GET request
response = requests.get(static_json_url)

# Check if the request was successful
print(response.status_code)  # Should print 200

# Step 2: Decode the response content as JSON
json_data = response.json()

# Step 3: Normalize the JSON data into a pandas DataFrame
df = pd.json_normalize(json_data)

# Display the first few rows of the DataFrame
df.head()

200

   flight_number      name                  date_utc                    rocket  success                 launchpad                    payloads  cores
0              1  FalconSat  2006-03-24T22:30:00.000Z  5e9d0d95eda69955f709d1eb    False  5e9e4502f5090995de566f86  [5eb0e4b5b6c3bb0006eeb1e1]   ...
1              2    DemoSat  2007-03-21T01:10:00.000Z  5e9d0d95eda69955f709d1eb    False  5e9e4502f5090995de566f86  [5eb0e4b5b6c3bb0006eeb1e2]   ...
2              3     Ratsat  2008-08-03T03:34:00.000Z  5e9d0d95eda69955f709d1eb    False  5e9e4502f5090995de566f86  [5eb0e4b5b6c3bb0006eeb1e3]   ...
3              4     RatSat  2008-09-28T23:15:00.000Z  5e9d0d95eda69955f709d1eb     True  5e9e4502f5090995de566f86  [5eb0e4b5b6c3bb0006eeb1e4]   ...
4              5   RazakSat  2009-07-13T03:35:00.000Z  5e9d0d95eda69955f709d1eb     True  5e9e4502f5090995de566f86  [5eb0e4b5b6c3bb0006eeb1e5]   ...

Using the dataframe <code>data</code> print the first 5 rows

You will notice that a lot of the data are IDs. For example the rocket column has no information about the rocket just an identification number.

We will now use the API again to get information about the launches using the IDs given for each launch. Specifically we will be using columns <code>rocket</code>, <code>payloads</code>, <code>launchpad</code>, and <code>cores</code>.

In [13]:
import datetime
import pandas as pd

# Assuming df is your original DataFrame from json_normalize
data = df.copy()

# Keep only the desired columns
data = data[['rocket', 'payloads', 'launchpad', 'cores', 'flight_number', 'date_utc']]

# Filter rows where 'cores' and 'payloads' lists have exactly one element
data = data[data['cores'].map(len) == 1]
data = data[data['payloads'].map(len) == 1]

# Extract the single element from the lists in 'cores' and 'payloads'
data['cores'] = data['cores'].map(lambda x: x[0])
data['payloads'] = data['payloads'].map(lambda x: x[0])

# Convert 'date_utc' to datetime and extract date only
data['date'] = pd.to_datetime(data['date_utc']).dt.date

# Filter launches up to November 13, 2020
data = data[data['date'] <= datetime.date(2020, 11, 13)]

* From the <code>rocket</code> we would like to learn the booster name

* From the <code>payload</code> we would like to learn the mass of the payload and the orbit that it is going to

* From the <code>launchpad</code> we would like to know the name of the launch site being used, the longitude, and the latitude.

* **From <code>cores</code> we would like to learn the outcome of the landing, the type of the landing, number of flights with that core, whether gridfins were used, whether the core is reused, whether legs were used, the landing pad used, the block of the core which is a number used to seperate version of cores, the number of times this specific core has been reused, and the serial of the core.**

The data from these requests will be stored in lists and will be used to create a new dataframe.

In [14]:
#Global variables 
BoosterVersion = []
PayloadMass = []
Orbit = []
LaunchSite = []
Outcome = []
Flights = []
GridFins = []
Reused = []
Legs = []
LandingPad = []
Block = []
ReusedCount = []
Serial = []
Longitude = []
Latitude = []

These functions will apply the outputs globally to the above variables. Let's take a looks at <code>BoosterVersion</code> variable. Before we apply  <code>getBoosterVersion</code> the list is empty:

In [15]:
BoosterVersion

[]

Now, let's apply <code> getBoosterVersion</code> function method to get the booster version

In [16]:
# Call getBoosterVersion
getBoosterVersion(data)

the list has now been update

In [17]:
BoosterVersion[0:5]

['Falcon 9', 'Falcon 9', 'Falcon 9', 'Falcon 9', 'Falcon 9']

we can apply the rest of the  functions here:

In [18]:
# Call getLaunchSite
getLaunchSite(data)

In [19]:
# Call getPayloadData
getPayloadData(data)

In [20]:
# Call getCoreData
getCoreData(data)

Finally lets construct our dataset using the data we have obtained. We we combine the columns into a dictionary.

In [21]:
launch_dict = {'FlightNumber': list(data['flight_number']),
'Date': list(data['date']),
'BoosterVersion':BoosterVersion,
'PayloadMass':PayloadMass,
'Orbit':Orbit,
'LaunchSite':LaunchSite,
'Outcome':Outcome,
'Flights':Flights,
'GridFins':GridFins,
'Reused':Reused,
'Legs':Legs,
'LandingPad':LandingPad,
'Block':Block,
'ReusedCount':ReusedCount,
'Serial':Serial,
'Longitude': Longitude,
'Latitude': Latitude}

Then, we need to create a Pandas data frame from the dictionary launch_dict.

In [22]:
# Create a data from launch_dict
df_launch = pd.DataFrame(launch_dict)

Show the summary of the dataframe

In [23]:
# Show the head of the dataframe
df_launch.head()

   FlightNumber        Date BoosterVersion  PayloadMass Orbit    LaunchSite      Outcome  Flights  GridFins  Reused   Legs LandingPad  Block  ReusedCount Serial   Longitude   Latitude
0             1  2010-06-04       Falcon 9          NaN   LEO  CCSFS SLC 40    None None        1     False   False  False       None    1.0            0  B0003  -80.577366  28.561857
1             2  2012-05-22       Falcon 9        525.0   LEO  CCSFS SLC 40    None None        1     False   False  False       None    1.0            0  B0004  -80.577366  28.561857
2             3  2013-03-01       Falcon 9        677.0   ISS  CCSFS SLC 40    None None        1     False   False  False       None    1.0            0  B0005  -80.577366  28.561857
3             4  2013-09-29       Falcon 9        500.0    PO   VAFB SLC 4E  False Ocean        1     False   False  False       None    1.0            0  B0006 -120.610829  34.632093
4             5  2013-12-03       Falcon 9       3170.0   GTO  CCSFS SLC 40  False Ocean        1     False   False  False       None    1.0            0  B0007  -80.577366  28.561857

### Task 2: Filter the dataframe to only include `Falcon 9` launches

Finally we will remove the Falcon 1 launches keeping only the Falcon 9 launches. Filter the data dataframe using the <code>BoosterVersion</code> column to only keep the Falcon 9 launches. Save the filtered data to a new dataframe called <code>data_falcon9</code>.

In [24]:
# Filter to only Falcon 9 launches (exclude Falcon 1)
data_falcon9 = df_launch[df_launch['BoosterVersion'] != 'Falcon 1']
data_falcon9.shape

(90, 17)

Now that we have removed some values we should reset the FlgihtNumber column

In [25]:
data_falcon9.loc[:,'FlightNumber'] = list(range(1, data_falcon9.shape[0]+1))
data_falcon9

    FlightNumber        Date BoosterVersion  PayloadMass  Orbit    LaunchSite      Outcome  ...  LandingPad  Block  ReusedCount Serial   Longitude   Latitude
0              1  2010-06-04       Falcon 9          NaN    LEO  CCSFS SLC 40    None None  ...        None    1.0            0  B0003  -80.577366  28.561857
1              2  2012-05-22       Falcon 9        525.0    LEO  CCSFS SLC 40    None None  ...        None    1.0            0  B0004  -80.577366  28.561857
..           ...         ...            ...          ...    ...           ...          ...  ...         ...    ...          ...    ...         ...        ...
88            89  2020-10-18       Falcon 9      15400.0   VLEO    KSC LC 39A    True ASDS  ...        ...    5.0            5  B1051  -80.603956  28.608058
89            90  2020-11-05       Falcon 9      15400.0   VLEO    KSC LC 39A    True ASDS  ...        ...    5.0            6  B1049  -80.603956  28.608058

[90 rows x 17 columns]


## Data Wrangling






We can see below that some of the rows are missing values in our dataset.

In [26]:
data_falcon9.isnull().sum()

FlightNumber     0
Date             0
BoosterVersion   0
PayloadMass      5
Orbit            0
LaunchSite       0
Outcome          0
Flights          0
GridFins         0
Reused           0
Legs             0
LandingPad      26
Block            0
ReusedCount      0
Serial           0
Longitude        0
Latitude         0
dtype: int64

Before we can continue we must deal with these missing values. The <code>LandingPad</code> column will retain None values to represent when landing pads were not used.

### Task 3: Dealing with Missing Values

Calculate below the mean for the <code>PayloadMass</code> using the <code>.mean()</code>. Then use the mean and the <code>.replace()</code> function to replace `np.nan` values in the data with the mean you calculated.

In [27]:
# Calculate the mean value of PayloadMass column
payload_mean = data_falcon9['PayloadMass'].mean()
print(f'Mean PayloadMass: {payload_mean:.2f} kg')

# Replace the np.nan values with its mean value
data_falcon9['PayloadMass'] = data_falcon9['PayloadMass'].replace(np.nan, payload_mean)

# Verify no more missing PayloadMass values
print(f'Missing PayloadMass values after imputation: {data_falcon9["PayloadMass"].isnull().sum()}')

Mean PayloadMass: 5956.42 kg
Missing PayloadMass values after imputation: 0

You should see the number of missing values of the <code>PayLoadMass</code> change to zero.

Now we should have no missing values in our dataset except for in <code>LandingPad</code>.

We can now export it to a <b>CSV</b> for the next section,but to make the answers consistent, in the next lab we will provide data in a pre-selected date range.

<code>data_falcon9.to_csv('dataset_part_1.csv', index=False)</code>

In [28]:
# Export the cleaned dataset to CSV for the next lab
data_falcon9.to_csv('dataset_part_1.csv', index=False)
print('dataset_part_1.csv saved successfully')
print(f'Final dataset shape: {data_falcon9.shape}')

dataset_part_1.csv saved successfully
Final dataset shape: (90, 17)

In [29]:
# Confirm remaining null values - only LandingPad should have missing entries
data_falcon9.isnull().sum()

FlightNumber     0
Date             0
BoosterVersion   0
PayloadMass      0
Orbit            0
LaunchSite       0
Outcome          0
Flights          0
GridFins         0
Reused           0
Legs             0
LandingPad      26
Block            0
ReusedCount      0
Serial           0
Longitude        0
Latitude         0
dtype: int64

In [30]:
# Final check: display first few rows of the clean dataset
data_falcon9.head()

   FlightNumber        Date BoosterVersion  PayloadMass Orbit    LaunchSite      Outcome  Flights  GridFins  Reused   Legs LandingPad  Block  ReusedCount Serial   Longitude   Latitude
0             1  2010-06-04       Falcon 9      5956.42   LEO  CCSFS SLC 40    None None        1     False   False  False       None    1.0            0  B0003  -80.577366  28.561857
1             2  2012-05-22       Falcon 9       525.00   LEO  CCSFS SLC 40    None None        1     False   False  False       None    1.0            0  B0004  -80.577366  28.561857
2             3  2013-03-01       Falcon 9       677.00   ISS  CCSFS SLC 40    None None        1     False   False  False       None    1.0            0  B0005  -80.577366  28.561857
3             4  2013-09-29       Falcon 9       500.00    PO   VAFB SLC 4E  False Ocean        1     False   False  False       None    1.0            0  B0006 -120.610829  34.632093
4             5  2013-12-03       Falcon 9      3170.00   GTO  CCSFS SLC 40  False Ocean        1     False   False  False       None    1.0            0  B0007  -80.577366  28.561857

## Authors

<a href="https://www.linkedin.com/in/joseph-s-50398b136/">Joseph Santarcangelo</a> has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.

<!--## Change Log
-->

<!--

|Date (YYYY-MM-DD)|Version|Changed By|Change Description|
|-|-|-|-|
|2020-09-20|1.1|Joseph|get result each time you run|
|2020-09-20|1.1|Azim |Created Part 1 Lab using SpaceX API|
|2020-09-20|1.0|Joseph |Modified Multiple Areas|
-->

Copyright ©IBM Corporation. All rights reserved.